server:
  port: 8081

spring:
  application:
    name: spring-cloud-client1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7100/eureka, http://127.0.0.1:8100/eureka, http://127.0.0.1:9100/eureka
    fetch-registry: true
    register-with-eureka: true
